modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="armor_expanded_medieval"
version="1.0.0"
displayName="Armor Expanded: Medieval"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.armor_expanded_medieval]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.armor_expanded_medieval]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.armor_expanded_medieval]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration